..

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -26,14 +26,16 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+
       - name: Lint with flake8
-        run: flake8 src/ tests/
+        run: |
+          flake8 src/
+          if [ $? -ne 0 ]; then
+            echo "Lint errors found. Failing build."; exit 1;
+          fi
 
       - name: Run pre-commit checks
         run: pre-commit run --all-files
-
-      - name: Run unit tests
-        run: pytest tests/
 
       - name: Azure ML login
         uses: azure/login@v2
